"""
Safety guardrails for medical AI responses.

- Mandatory disclaimers
- Audit logging to PostgreSQL
- Citation enforcement
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone

from src.config import get_db_connection

# ---------------------------------------------------------------------------
# Disclaimer
# ---------------------------------------------------------------------------

_DISCLAIMER = (
    "**Medical Disclaimer:** This information is generated by an AI system "
    "and is intended for informational purposes only.  It does NOT constitute "
    "medical advice, diagnosis, or treatment.  Always consult a qualified "
    "healthcare professional before making clinical decisions.\n\n"
)


def add_disclaimer(response: str) -> str:
    """Prepend a standard medical disclaimer to *response*."""
    return _DISCLAIMER + response


# ---------------------------------------------------------------------------
# Citation enforcement
# ---------------------------------------------------------------------------

# Matches patterns like [Source: some reference]
_CITATION_RE = re.compile(r"\[Source:\s*[^\]]+\]")


def enforce_citations(response: str) -> bool:
    """Check whether *response* contains at least one ``[Source: ...]`` citation.

    Returns
    -------
    bool
        ``True`` if at least one citation is found; ``False`` otherwise.
    """
    return bool(_CITATION_RE.search(response))


# ---------------------------------------------------------------------------
# Audit logging
# ---------------------------------------------------------------------------

_AUDIT_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    action      TEXT NOT NULL,
    query       TEXT,
    response    TEXT,
    sources     JSONB DEFAULT '[]',
    created_at  TIMESTAMPTZ DEFAULT now()
);
"""


def _ensure_audit_table() -> None:
    conn = get_db_connection()
    conn.execute(_AUDIT_TABLE_SQL)


def audit_log(
    action: str,
    query: str,
    response: str,
    sources: list | None = None,
) -> None:
    """Write an entry to the ``audit_log`` table.

    Parameters
    ----------
    action:
        Short label describing the operation (e.g., ``"rag_query"``).
    query:
        The user's original query.
    response:
        The AI-generated response.
    sources:
        List of source identifiers cited in the response.
    """
    _ensure_audit_table()
    conn = get_db_connection()
    conn.execute(
        """
        INSERT INTO audit_log (action, query, response, sources)
        VALUES (%s, %s, %s, %s::jsonb)
        """,
        (action, query, response, json.dumps(sources or [])),
    )
